### ISSUE TITLE
Project layout change request

### ISSUE THREAD

**Issue by ptr727** [gjbadros/hass-vantage#20]
The current project layout does not make a clear separation between `custom_components/vantage` and the rest of the project.  
E.g. copying the project requires `hass-vantage` to be renamed to `vantage` as that is what is used to reference the objects in HA.  
E.g. the test files, readme, etc., now live in the HA folder.

I suggest you follow the pattern used by other custom components where the project contains a `custom_components/vantage` directory where only the HA goodies go, and the remainder of the project can be dedicated to boilerplate, graphics, readme, test code, etc.

e.g. see [Purple Air](https://gitlab.com/gibwar/home-assistant-purpleair) and [Flair](https://github.com/RobertD502/home-assistant-flair).

**Comment by gjbadros** [comment]
Is your concern resolved by https://github.com/gjbadros/hass-vantage/pull/16 -- I just merged that.

**Comment by ptr727** [comment]
Yes, thank you

**Comment by stevespaw** [comment]
Does this allow use in HassOS as in https://github.com/gjbadros/hass-vantage/issues/19 ? If so, I am excited to give it a go. Are there new install instructions?  Thanks

**Comment by gjbadros** [comment]
I don't know, give it a try and report back.

**Comment by stevespaw** [comment]
I have just looked at, and installed the HACS system in HA. https://hacs.xyz/ This is cool. I was able to integrate my Wyze devices with it. When this Vantage Integration is done, it will be great. https://hacs.xyz/docs/publish/start I assume it is not there yet, since it is not in the repository. I will keep looking for this, Thanks
