### ISSUE TITLE
No ability to configure SSL connectivity

### ISSUE THREAD

**Issue by ptr727** [gjbadros/hass-vantage#23]
I upgraded my aging IC36 to an IC36-II, and v4.5 Design Center.
SSL is enabled, and SSL ports are 2010 and 3010.

Other than forking the code and hand coding to enable SSL and 2010 and 310, is there an alternative I overlooked?

**Comment by gjbadros** [comment]
I just merged my ADD_USE_SSL_OPTION branch to master -- it adds "use_ssl: true" as a hass option for the vantage setup
